[Custom_WriteList_XXX]
Enable = true                           # 是否启用此功能

#机器人配置
Robotname = "麻了"      #机器人昵称，务必设置准确，否则会影响@机器人时的启用
Wxid = "wxid_27q2wvyh9j1p21"              #机器人Wxid

#个体白名单功能，可以针对某一个群开启，仅限管理员
One_Chat_Mode=false     #私聊是否所有人可用，true为所有人私聊可用，false为白名单内人员私聊可用（请将过滤模式改为不过滤或黑名单模式）
Wake_Word="/on"        #唤醒词，根据喜好自行设置，例：原神，启动！
Sleep_Word="/off"      #退出词，根据喜好自行设置
Welcome_Word="服务已启动，欢迎使用！"    #欢迎词，根据喜好自行设置
Goodbye_Word="服务已退出，谢谢使用！"    #再见词，根据喜好自行设置



